### ISSUE TITLE
Can’t write `_apolloObservable` to frozen cache results

### ISSUE THREAD

**Issue by charlesdemers** [ember-graphql/ember-apollo-client#332]
👋 Hi! I just want to report a problem I had, I’m not sure if you want to change the implementation or simply provide info on the problem in the README to avoid this.

In short, when updating to `2.0.0` I had this message pop up in my terminal:

```
webpack://__ember_auto_import__/./node_modules/zen-observable/lib/Observable.js?:82
      throw e;
      ^

TypeError: Cannot define property _apolloObservable, object is not extensible
    at Function.defineProperty (<anonymous>)
    at Object.newData [as next] (/tmp/broccoli-82246w72X84e8A5Xe/out-394-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-apollo-client/services/apollo.js:61:1)
    at notifySubscription (webpack://__ember_auto_import__/./node_modules/zen-observable/lib/Observable.js?:152:18)
    at flushSubscription (webpack://__ember_auto_import__/./node_modules/zen-observable/lib/Observable.js?:138:5)
    at eval (webpack://__ember_auto_import__/./node_modules/zen-observable/lib/Observable.js?:191:14)
    at eval (webpack://__ember_auto_import__/./node_modules/zen-observable/lib/Observable.js?:90:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I wasn’t sure what the problem was and found out that you have a `getObservable` function which writes in the query results. After trying a few things, I found that my cache configuration was the problem:

```ts
const cache = new InMemoryCache({
  freezeResults: true
});
```

When you create an `InMemoryCache` instance with the `freezeResults` flag set to `true`, the results are frozen so the key can’t be added to the object, hence the error.

Tell me if I can help!

✌️

**Comment by josemarluedke** [comment]
Thanks for reporting this. I will consider this as a bug and I will have a look at this in the coming days.
