### ISSUE TITLE
ember-apollo-client not working with GlimmerJS blueprint

### ISSUE THREAD

**Issue by kiannaquach** [ember-graphql/ember-apollo-client#336]
Hi, I tried to install `ember-apollo-client` to my Glimmer blueprint app and ran into some issues. I attached the error summary below. Does `ember-apollo-client` support Glimmer? Thank you!!

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'bind' of undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'bind' of undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'bind' of undefined
    at AutoImport.included (/Users/kiannaq./Desktop/glimmer-example-1/node_modules/ember-auto-import/js/auto-import.js:103:50)
    at Class.included (/Users/kiannaq./Desktop/glimmer-example-1/node_modules/ember-auto-import/js/index.js:29:24)
    at Class.superWrapper [as included] (/Users/kiannaq./Desktop/glimmer-example-1/node_modules/core-object/lib/assign-properties.js:34:20)
    at /Users/kiannaq./Desktop/glimmer-example-1/node_modules/ember-cli/lib/models/addon.js:405:26
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/Users/kiannaq./Desktop/glimmer-example-1/node_modules/ember-cli/lib/models/addon.js:402:24)
    at Class.included (/Users/kiannaq./Desktop/glimmer-example-1/node_modules/ember-cli/lib/models/addon.js:678:10)
    at Class.superWrapper [as included] (/Users/kiannaq./Desktop/glimmer-example-1/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class.included (/Users/kiannaq./Desktop/glimmer-example-1/node_modules/ember-apollo-client/index.js:25:26)
    at Class.superWrapper [as included] (/Users/kiannaq./Desktop/glimmer-example-1/node_modules/core-object/lib/assign-properties.js:34:20)

```

**Comment by josemarluedke** [comment]
Hello @kiannaquach. Unfortunately, this project does not work with the standalone Glimmer.js project.
It only works in an Ember project. Now, if you are using [Ember Octane](https://emberjs.com/editions/octane), which has Glimmer components, then that does work.
